# -*- mode: ruby -*-
# vi: set ft=ruby :

vmIP = "192.168.33.10"

Vagrant.configure(2) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: vmIP

  # All Vagrant configuration is done below. The "2" in Vagrant.configure
  # configures the configuration version (we support older styles for
  # backwards compatibility). Please don't change it unless you know what
  # you're doing.
  config.vm.provision "shell", privileged: true, path: "install.sh"

  config.vm.provision "shell", privileged: false, run: "always" do |s|
    s.inline = "cd /vagrant && jupyter-notebook --ip='#{vmIP}' --no-browser &"
  end

end
